existingSecret: "buzz"

endpoints:
  cluster_domain_suffix: cluster.local
  oslo_db:
    auth:
      buzz:
        username: USERNAME
        password: PASSWORD
    hosts:
      default: mariadb
    host_fqdn_override:
      default: null
    path: /nova
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306

conf:
  buzz:
    DEFAULT:
      param: value
    database:
      max_retries: -1

manifests:
  configmap_etc: true
